backend:
  replicaCount: 1

  image:
    tag: "latest"

  route:
    host: cas-reporting-backend-test.apps.silver.devops.gov.bc.ca

  environment: test

frontend:
  replicaCount: 1

  image:
    tag: "latest"

  route:
    host: cas-reporting-frontend-test.apps.silver.devops.gov.bc.ca

  environment: test

  auth:
    keycloakAuthUrl: https://test.loginproxy.gov.bc.ca/auth
    siteminderAuthUrl: https://logontest7.gov.bc.ca
