kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "cas-reporting.fullname" . }}-backend-postgres-ingress
  labels: {{ include "cas-reporting.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.database.releaseName }}
  ingress:
    - from:
        - podSelector:
            matchLabels:
              release: {{ .Release.Name }}
              component: backend
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ .Release.Name }}
              component: backend
