name: pytest

on:
  push:
    branches: [main, develop, 73-initialize-pytest]
  pull_request:
    branches: [main, develop, 73-initialize-pytest]

jobs:
  install-dev-tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: dev env setup
        uses: ./.github/actions/dev-env-setup
      - run: yarn install --frozen-lockfile
        working-directory: ./client
  backend-tests:
    needs:
      ["install-dev-tools"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: dev env setup
        uses: ./.github/actions/dev-env-setup
      - name: Run pytest
        working-directory: ./bc_obps
        run: make pythontests